# 🌐 Get Render Deployment URL Script

Write-Host "======================================================" -ForegroundColor Cyan
Write-Host "   Finding Your Render Deployment URL                " -ForegroundColor White
Write-Host "======================================================" -ForegroundColor Cyan
Write-Host ""

Write-Host "Your project: steel-manufacturing-system" -ForegroundColor Yellow
Write-Host "GitHub repo: https://github.com/VYOMSAHU2003/steel-manufacturing-system" -ForegroundColor Green
Write-Host ""

# Check if deployment exists
Write-Host "🔍 Checking deployment status..." -ForegroundColor Cyan
Write-Host ""

Write-Host "📋 To get your direct Render URL:" -ForegroundColor Yellow
Write-Host ""  
Write-Host "Method 1 - Check Render Dashboard:" -ForegroundColor White
Write-Host "1. Go to: https://dashboard.render.com" -ForegroundColor Cyan
Write-Host "2. Sign in with your GitHub account" -ForegroundColor White
Write-Host "3. Look for 'steel-manufacturing-system' service" -ForegroundColor White
Write-Host "4. Click on it to see the live URL" -ForegroundColor White
Write-Host ""

Write-Host "Method 2 - If not deployed yet:" -ForegroundColor White
Write-Host "1. Go to: https://dashboard.render.com" -ForegroundColor Cyan
Write-Host "2. Click 'New +' → 'Web Service'" -ForegroundColor White
Write-Host "3. Connect repository: steel-manufacturing-system" -ForegroundColor White
Write-Host "4. Click 'Deploy' (settings auto-configured)" -ForegroundColor White
Write-Host "5. Wait 3-5 minutes for deployment" -ForegroundColor White
Write-Host "6. Get your live URL!" -ForegroundColor Green
Write-Host ""

Write-Host "🌐 Your URL will look like:" -ForegroundColor Yellow
Write-Host "https://steel-manufacturing-system-XXXX.onrender.com" -ForegroundColor Cyan
Write-Host "(where XXXX is a random string generated by Render)" -ForegroundColor Gray
Write-Host ""

Write-Host "Opening Render dashboard to check your deployment..." -ForegroundColor Cyan
Start-Process "https://dashboard.render.com"

Write-Host ""
Write-Host "🎯 Quick Deploy (if needed):" -ForegroundColor Yellow
Write-Host "If your service isn't deployed yet, it takes just 2-3 clicks:" -ForegroundColor White
Write-Host "- Connect repository" -ForegroundColor White  
Write-Host "- Click Deploy" -ForegroundColor White
Write-Host "- Wait 3-5 minutes" -ForegroundColor White
Write-Host "- Get your live URL!" -ForegroundColor Green
Write-Host ""

$response = Read-Host "Press Enter after checking Render dashboard (or type your URL if you found it)"

if ($response -and $response.Contains("http")) {
    Write-Host ""
    Write-Host "🎉 Great! Your Steel Manufacturing System is live at:" -ForegroundColor Green
    Write-Host $response -ForegroundColor Cyan
    Write-Host ""
    Write-Host "Opening your live app..." -ForegroundColor Yellow
    Start-Process $response
    Write-Host ""
    Write-Host "✅ Your app features:" -ForegroundColor Green
    Write-Host "- Raw Materials Management" -ForegroundColor White
    Write-Host "- Production Planning" -ForegroundColor White  
    Write-Host "- Quality Assurance" -ForegroundColor White
    Write-Host "- Logistics & Shipment" -ForegroundColor White
    Write-Host "- Analytics Dashboard" -ForegroundColor White
} else {
    Write-Host ""
    Write-Host "📱 If you need to deploy:" -ForegroundColor Yellow
    Write-Host "1. Your repository is ready: ✅" -ForegroundColor Green
    Write-Host "2. render.yaml is configured: ✅" -ForegroundColor Green  
    Write-Host "3. Just connect on Render dashboard" -ForegroundColor White
    Write-Host "4. Deployment takes 3-5 minutes" -ForegroundColor White
    Write-Host ""
    Write-Host "🔄 Auto-deploy is enabled - future pushes deploy automatically!" -ForegroundColor Green
}

Write-Host ""
Write-Host "Happy manufacturing!" -ForegroundColor Cyan